### ISSUE TITLE
Lootin does not respect world guard use chest permissions

### ISSUE THREAD

**Issue by FaultyFunctions** [sachingorkar102/Lootin-plugin#28]
Hello! I have world guard installed on my server and it prevents users of the "guest" rank to not open chests, however they can still open lootin chests even though in chat it says "You can't do that".

**Comment by sachingorkar102** [comment]
you can set the wg flag value for "lootin-container-access" to false for the "guest" users

**Comment by FaultyFunctions** [comment]
Oh my bad I didn't know that was a thing, thank you!
