### ISSUE TITLE
Bastion Loot Chest Issue

### ISSUE THREAD

**Issue by TheMattVid** [sachingorkar102/Lootin-plugin#33]
Hello! I have an issue with a chest in a bastion. Players can open it once, and then they are no longer able to open it a second time. There is an error in the console when this occurs. I am not sure if this is happening at any other loot chests.

Here is the error:
https://mclo.gs/OJrJX3y

Running on Purpur (A fairly common fork of Paper)
Purpur Version: 1.21.1-2286-366af80 (MC: 1.21.1)
Lootin Version: 10.6

**Comment by sachingorkar102** [comment]
that should be fixed in latest 10.7 version
