### ISSUE TITLE
[feature request] Add a "last looted" condition

### ISSUE THREAD

**Issue by quiquelhappy** [sachingorkar102/Lootin-plugin#6]
Hello,
First of all, thanks for this resource! I love it and it seems to be working great! I've being testing it on 1.18 and the only issue I found is the chest opening sound playing twice, which is most likely being caused by ProtocolLib not having a final release yet.

I'd like to have an option called ``last-loot: x<time unit>`` that not only makes the loot per player, but also only shows the loot if the thing hasn't been loted for the past [defined time].

## Example: ``last-loot: 10d``
The loot will only be shown to players that **haven't looted the thing** as long as no other player looted it for the past **10 days**. The players are only able to loot whatever thing just one time (just like the actual release), but the loot wont be available if it has been looted by some other player in the past 10 days.

This would apply to everything, including elytras, that's why im using the word "thing". 

## Why?
This would help make the server feel more vanilla-like while still making sure players have a high chance of finding loot. It's the perfect thing since compared to a general loot reset plugin, the players that already loot whatever thing can only get the loot once.

**Comment by sachingorkar102** [comment]
that sounds like a neat addition but i don't want to take lootin to that path,i want it to stay as close to lootr as possible, so this might not be added sorry ^^
