### ISSUE TITLE
onPacketSending Error on chest opening

### ISSUE THREAD

**Issue by Edrow-6** [sachingorkar102/Lootin-plugin#7]
Hi, i have an error in the console, can you help me?
https://mclo.gs/rFwyBD7

**Comment by Edrow-6** [comment]
Dude the minimum of respect is to reply on my ticket before closing it

**Comment by Edrow-6** [comment]
You make a plugin, this plugin doesn't work, your job is to help for debugging because it's your's...

**Comment by sachingorkar102** [comment]
It was rude now donate 6940$ >:)
